<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PRICE_noUi-handle noUi-handle-lower</name>
   <tag></tag>
   <elementGuidId>d32f64a2-1289-438f-a062-eb3ba06fa986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slider']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.noUi-handle.noUi-handle-lower</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>32018fe8-ea85-406b-9e06-6e6a47b74796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noUi-handle noUi-handle-lower</value>
      <webElementGuid>2fb1239a-3005-4325-84b5-9fa8fb7bff7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider&quot;)/div[@class=&quot;noUi-base&quot;]/div[@class=&quot;noUi-origin noUi-connect&quot;]/div[@class=&quot;noUi-handle noUi-handle-lower&quot;]</value>
      <webElementGuid>97ce59a1-1ef1-4649-bb83-a0e2e69ee8da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider']/div/div/div</value>
      <webElementGuid>4f2ef95b-3f8a-45fa-8e38-cf58f8267abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/div</value>
      <webElementGuid>5b0123ac-4dd3-46d7-b857-2ac8c70c2c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
