<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign out_autoComplete</name>
   <tag></tag>
   <elementGuidId>eb14187c-90b2-421e-889e-c3f69c20c749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autoComplete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#autoComplete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c596140-ee09-42a4-9705-b85c1eef57d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autoComplete</value>
      <webElementGuid>d0fe9e66-b47e-4265-843c-d6a426d859ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0179369-e6dc-47fc-9d2e-d97d02f9ae3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular ng-pristine ng-valid ng-touched</value>
      <webElementGuid>dac2d89b-e98a-45e5-b7a4-8014c8740183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search AdvantageOnlineShopping.com</value>
      <webElementGuid>04966eed-effa-41d5-9ade-d78df73ecccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keypress</name>
      <type>Main</type>
      <value>checkEnterKey($event)</value>
      <webElementGuid>b34461f8-2ba2-441f-9f1f-846d76f61c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>autoCompleteValue</value>
      <webElementGuid>355b29a4-f060-414b-9216-159a14cc8431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keyup</name>
      <type>Main</type>
      <value>runAutocomplete()</value>
      <webElementGuid>dc1754c5-36e3-4227-81d5-e7ca06202d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoComplete&quot;)</value>
      <webElementGuid>b9016ad2-bcbc-47e6-8230-b5d2328153f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autoComplete']</value>
      <webElementGuid>bb04dd8b-249f-4528-84a1-63481b155182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/input</value>
      <webElementGuid>40eee9e8-0221-4686-a2c4-ac0eabd6a853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>7138c4ab-2421-4a67-a1db-17ee0359f2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autoComplete' and @type = 'text' and @placeholder = 'Search AdvantageOnlineShopping.com']</value>
      <webElementGuid>3f1ac67b-5e90-4d32-b312-7af48402cb20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
