<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Clear</name>
   <tag></tag>
   <elementGuidId>c60e8c60-da26-49ae-82ae-c975bd7f0172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mobileSlide']/label/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.roboto-regular.clear.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>da370808-185e-413f-b853-207d2546d488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular clear ng-scope</value>
      <webElementGuid>232515c3-3b52-4f91-a7ed-204ee13a02c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>clearSelection()</value>
      <webElementGuid>b97b5b12-c196-4585-ad37-854169881c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>edef7102-bd33-471c-98ae-6ebe14596571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>showClear</value>
      <webElementGuid>0f58461e-91ef-48f5-a23b-66f3a3425159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>b8cd5649-da13-41b6-8f64-92e8ea2785c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileSlide&quot;)/label[@class=&quot;roboto-regular ng-binding&quot;]/label[@class=&quot;roboto-regular clear ng-scope&quot;]</value>
      <webElementGuid>273c90b1-641b-4775-99fb-733ba2c42b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/label/label</value>
      <webElementGuid>f6875754-818e-4995-ae8f-58b958074239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORIES'])[2]/preceding::label[1]</value>
      <webElementGuid>248d0152-a80d-4b44-a217-36598c0ec664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAPTOPS'])[1]/preceding::label[1]</value>
      <webElementGuid>c004104b-bd5b-4248-90dc-d28fafbc8a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear']/parent::*</value>
      <webElementGuid>663b3ad2-a851-4ad8-82bf-df5a294f3858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/label</value>
      <webElementGuid>c61b84ca-19d6-4590-89aa-3651d32b3a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Clear' or . = 'Clear')]</value>
      <webElementGuid>99bf130b-4ff9-44be-908a-66724a3d442c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
