<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_SafePay username</name>
   <tag></tag>
   <elementGuidId>91a18331-4ce8-45a1-a54a-1d33818eeae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paymentMethod']/div/div[2]/sec-form/sec-view/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > sec-form.ng-isolate-scope.secForm > sec-view.ng-isolate-scope.sec-view > div.inputContainer.ng-scope > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f13f45af-8647-4401-93cc-f007d9e7ca22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>labelClicked()</value>
      <webElementGuid>80dd66a1-7f97-4d75-9b6f-3ccd0874616d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-mouseout</name>
      <type>Main</type>
      <value>labelOut()</value>
      <webElementGuid>a04353a4-30d3-4024-bd8a-09d23ebbb146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SafePay username</value>
      <webElementGuid>69d8efd9-109d-41c5-817c-ce9eb763ebaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[2]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/label[1]</value>
      <webElementGuid>ce72886f-0cb1-4e12-957a-34d802d19694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[2]/sec-form/sec-view/div/label</value>
      <webElementGuid>f5a5624b-ef5f-49d5-aaa9-7b0e1dda4dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::label[1]</value>
      <webElementGuid>a91180ad-1469-4f73-839d-1aae174c079a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notice'])[1]/following::label[2]</value>
      <webElementGuid>92931bbf-f32b-4977-8ea5-4dcbb7c64c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Use maximum 15 character'])[1]/preceding::label[1]</value>
      <webElementGuid>f1ff8c4c-16df-47e9-a526-7fa8471a2468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/sec-form/sec-view/div/label</value>
      <webElementGuid>ddddc040-b04c-49d0-bbc6-38bfc2f5a401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'SafePay username' or . = 'SafePay username')]</value>
      <webElementGuid>761ce6b9-4e58-49ea-b3b2-34ddc917d00f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
