<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_PROCESSOR</name>
   <tag></tag>
   <elementGuidId>2bbc105e-9f7c-4890-9f67-88e348746b00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='accordionAttrib1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accordionAttrib1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>01bf0254-faac-4163-aaca-8625d911e673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>fa56757c-0b3d-4846-bea1-750bb29c9168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion roboto-regular arrowDown ng-binding</value>
      <webElementGuid>6f7c01b6-1497-49ba-ae03-8b6c424e5e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordionAttrib1</value>
      <webElementGuid>b53ec430-8751-4ef2-afca-987d611958e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleColapse('accordionAttrib' + $index)</value>
      <webElementGuid>1f0875aa-dee7-4c25-b5ca-cfa279900c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>dbe54c07-a4c7-479f-9770-de83ca5dd05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        PROCESSOR
                    </value>
      <webElementGuid>74c7d457-f721-49da-ad64-89a8c43e107d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionAttrib1&quot;)</value>
      <webElementGuid>01d51f26-55dd-47c7-95b7-71b5818258ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='accordionAttrib1']</value>
      <webElementGuid>ff83df75-4d46-4a7f-9766-a09f9d9828d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/h4</value>
      <webElementGuid>b046002f-9267-485d-9967-7d6109096664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISPLAY'])[1]/following::h4[1]</value>
      <webElementGuid>33694a17-bf6c-4b80-b64b-65fee7e1060e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intel® Atom® Z3795 (1.6 GHz, up to 2.39 GHz using Intel Burst Technology, 2 MB cache, 4 cores)'])[1]/preceding::h4[1]</value>
      <webElementGuid>8dedd90b-e829-43c0-84f6-5cbde1bc1e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COLOR'])[1]/preceding::h4[1]</value>
      <webElementGuid>d9d7d7ed-af16-4549-9cdd-1c220f7438b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROCESSOR']/parent::*</value>
      <webElementGuid>f0d822b1-92ae-4a3a-9405-b67b6c0f0e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/h4</value>
      <webElementGuid>4daa60e3-675b-4d08-9d88-31056ace4007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@href = 'javascript:void(0)' and @id = 'accordionAttrib1' and (text() = '
                        PROCESSOR
                    ' or . = '
                        PROCESSOR
                    ')]</value>
      <webElementGuid>3b8ab908-7a99-464a-aab3-a8d32f7e0908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('7.9', '&quot;', ' diagonal FHD multi-touch display with Corning® Gorilla® Glass® (2048 x 1536)')])[1]/following::h4[1]</value>
      <webElementGuid>1ab79ea0-00ea-4248-94d4-a165d6eb31fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
