<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PROCESSOR_processor_0</name>
   <tag></tag>
   <elementGuidId>feba2af4-c258-44d8-bbd5-965d5beaf7b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='processor_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#processor_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>510c5473-8715-4710-976c-2da35b306960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>processor_0</value>
      <webElementGuid>ff43f7b0-ebc2-49ca-bb21-af9ef74526b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>34317aa2-a593-464b-92ad-5d66de4f4103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>item.selected</value>
      <webElementGuid>6b27e59d-35e6-4b36-8e9f-d0cf2acacc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(attrVal, attrib.name)</value>
      <webElementGuid>149a0737-ddba-49a5-830b-40573b341517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>processor_0</value>
      <webElementGuid>3613b853-e18c-4d9e-906a-440e87288f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>fb9e904e-4d42-4181-9478-576f6b005a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;processor_0&quot;)</value>
      <webElementGuid>e973cac1-5baa-474b-9028-f7ab64ee7dd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='processor_0']</value>
      <webElementGuid>d6a828e0-5882-433e-8305-dcd02e056ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/div/div/div/input</value>
      <webElementGuid>597fbe58-65bd-452f-be73-963f5d5ec97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/input</value>
      <webElementGuid>8a6de0fc-8e66-482b-9599-498032e1a2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'processor_0' and @type = 'checkbox' and @id = 'processor_0']</value>
      <webElementGuid>a946ac4a-3dc6-4a1a-bd39-33ec63bd9a3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
