<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Intel Atom Z3795 (1.6 GHz, up to 2.39_c4bb3e</name>
   <tag></tag>
   <elementGuidId>61f44e31-186d-4576-8136-45522e31c1e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='processor_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#processor_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18ebf753-bfdc-443d-aa4f-fc4277984c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>processor_1</value>
      <webElementGuid>7d5ac5d6-b54a-4718-9018-511cfa980037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>047b10c0-b043-4fe1-90c5-2835b9775487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>item.selected</value>
      <webElementGuid>3394790d-2628-48b2-8bd1-ce20e34a27d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(attrVal, attrib.name)</value>
      <webElementGuid>2036b60f-f03a-430e-bfb7-0c6a11107ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>processor_1</value>
      <webElementGuid>d524543e-f113-4bb1-9fb6-d8473e47a535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>7f918f4a-15a4-4441-923d-445739ea609b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;processor_1&quot;)</value>
      <webElementGuid>bea30330-9057-4f93-8d51-6827f97db172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='processor_1']</value>
      <webElementGuid>5b960124-0d61-4feb-860c-5481b63a5881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/div/div[2]/div/input</value>
      <webElementGuid>e9fec429-eb6c-40a6-bdb0-e45ae2fa42e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/div/input</value>
      <webElementGuid>d866f066-e1c2-4609-aee6-78d63144c510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'processor_1' and @type = 'checkbox' and @id = 'processor_1']</value>
      <webElementGuid>e283618e-5a73-418c-87b4-be1b395b44ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
