<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_cintilu.cu</name>
   <tag></tag>
   <elementGuidId>469270c0-e29e-446a-aec8-2ce9ad9b9c46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.hi-user.containMiniTitle.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuUserLink']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4aa77484-4519-4bd5-8f5a-abb1186d680b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>userCookie.response</value>
      <webElementGuid>da2698b7-90f3-4c33-865f-82ce68f96f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hi-user containMiniTitle ng-binding</value>
      <webElementGuid>1609a1e4-df88-4452-831b-aa4cbf828564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cintilu.cu</value>
      <webElementGuid>4375d0bc-6535-483e-8175-c89ef34623c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuUserLink&quot;)/span[@class=&quot;hi-user containMiniTitle ng-binding&quot;]</value>
      <webElementGuid>da7c01e4-8d78-42bc-a133-0b359a609886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuUserLink']/span</value>
      <webElementGuid>5d688dbe-5efe-4cda-a806-387a57b7fa81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::span[1]</value>
      <webElementGuid>fa416b0a-0f7e-4c9c-b3e3-7499674e22e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::span[1]</value>
      <webElementGuid>cfcca143-aa22-45d0-9343-32f4de85d838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/preceding::span[1]</value>
      <webElementGuid>2ac9acd1-06b3-4091-95e7-07e695b5e131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a/span</value>
      <webElementGuid>5bc8217e-fc08-461d-b85f-8988caae3adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'cintilu.cu' or . = 'cintilu.cu')]</value>
      <webElementGuid>57e9a74c-590b-44c9-ada7-0d8f67602e10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
